version: "3"

services:
    react_app:
        build: ./client
        ports:
            - 4200:4200
        volumes:
            - ./client/:/app
        environment:
            - REACT_APP_JWT_SECRET=BCDIRY
            - WATCHPACK_POLLING=true
            - CHOKIDAR_USEPOLLING=true
        stdin_open: true

    express_app:
        build: ./server
        ports:
            - 3000:3000
        volumes:
            - ./server/:/app
        environment:
            - DB_NAME=intearactivepsetDB
            - DB_HOST=db_server
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=password
            - JWT_SECRET=BCDIRY
        depends_on:
            - db_server
        command: "bash start.sh db_server:3306"

    db_server:
        image: mysql:latest
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=intearactivepsetDB

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        container_name: redis-container


