version: "3"

services:
    react_app:
        build: ./client
        ports:
            - 4200:4200
        volumes:
            - ./client/:/app

    express_app:
        build: ./server
        ports:
            - 3000:3000
        volumes:
            - ./server/:/app
        environment:
            - DB_NAME=intearactivepsetDB
            - DB_HOST=db_server
            - DB_PORT=3306
            - DB_USER=root
            - DB_PASSWORD=password
        depends_on:
            - db_server
        command: "bash start.sh db_server:3306"

    db_server:
        image: mysql:5.7
        ports:
            - "25012:25012"
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=intearactivepsetDB

    redis:
        image: redis
        ports:
            - "6379:6379"


